#!/bin/bash
# This should be used to startup a random number of services
# as every other directory here is a rails application
# should eventually add a line /etc/rc.local to source this file
apps=( services convert pi quad fib )
ports=( 3000 1210 3141 4416 3001 )

for i in 0 1 2 3 4
do
    cd "${OS_PROJ_HOME}/${apps[i]}"
    `script/server -p ${ports[i]} </dev/null &>/dev/null &`
done
